default: &default
  adapter: postgresql
  encoding: unicode
  username: developer
  password: developer
  host: localhost

development:
  <<: *default
  database:  my-wallet-app
  username: developer
  password: developer

test:
  <<: *default
  database:  my-wallet-app
  username: developer
  password: developer

production:
  <<: *default
  url: <%= ENV['DATABAS_URL']%>
