default: &default
  adapter: postgresql
  encoding: unicode
  username: developer
  password: developer
  host: localhost

development:
  <<: *default
  database: your_development_db_name
  username: developer
  password: developer

test:
  <<: *default
  database: your_test_db_name
  username: developer
  password: developer

production:
  <<: *default
  url: <%= ENV['DATABAS_URL']%>
